# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalculateRealWater <- function(xev, xrf, xmin, xmax, xui, xday) {
    .Call('CNew_CalculateRealWater', PACKAGE = 'CNew', xev, xrf, xmin, xmax, xui, xday)
}

SpilloverW <- function(xw0, xwmax, xreal) {
    .Call('CNew_SpilloverW', PACKAGE = 'CNew', xw0, xwmax, xreal)
}

